### Upload file
POST http://localhost:8081/attach/upload
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQyMjYxODksInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQzMTI1ODksImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.LTC4yVU5Udkv4i4ONDq-I5ow14WijGoTkkO0PriLO8C7zxgwxH9SsHA85Eyl3OrYhm40x0rUknhtsN1VrrXwxQ
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo_png.png"

< C:\Users\user\Desktop\photo_png.png




### open
GET http://localhost:8081/attach/public/open/1

### delete
DELETE http://localhost:8081/attach/delete/1