### Upload file
POST http://localhost:8081/attach/upload
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE4MTUwNDUsInVzZXJuYW1lIjoibmF6YXJvdmF6aW1qb244ODhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MTkwMTQ0NSwiaXNzIjoia3VudXogdGVzdCBwb3J0YWxpIn0.GU4r5078UXpP4gJcNr7pkru0-lk9J0paeU-8VhaZpz49JBMJe6Y0dUKAWJRTdUjUZbevcvi6hWHNaXGZVTQvaw
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="rasm.jpg"

< C:\Users\user\Desktop\rasm.jpg




### open
GET http://localhost:8081/attach/open/26

### delete
DELETE http://localhost:8081/attach/delete/27