### CREATE INNER CATEGORY
POST http://localhost:8081/innerCategory/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQyODg4NjEsInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQzNzUyNjEsImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.3pFdyYniLSJebd-LhAraAvt6bfc8YpFnPIB1BP9hptqCo6ASfIKzWhi9JqnPjbSxXrrlIsXCX84KucjP47oP9A

{
  "photo": 2,
  "category": 1,
  "nameUz": "2222222222",
  "nameRu": "Сладости222222222",
  "descriptionUz": "Medovik tortlar dsdsdsdsdsdsds",
  "descriptionRu": "Торты Медовик dsdsdsdsdsdsdsd"

}

### UPDATE INNER CATEGORY
PUT http://localhost:8081/innerCategory/update/1
Content-Type: application/json
Authorization: Bearer

{
  "photo": 2,
  "category": 1,
  "nameUz": "Shirinliklar Update",
  "nameRu": "Сладости Update",
  "descriptionUz": "Medovik tortlar Update",
  "descriptionRu": "Торты Медовик Update"
}

### GET INNER CATEGORY WITH PAGENATION
GET http://localhost:8081/innerCategory/public/getList/UZ?page=0&size=10
### GET FROM ADMIN INNER CATERGORY WITH PAGINATION
GET http://localhost:8081/innerCategory/getListAll?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQxMzIyMzksInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQyMTg2MzksImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.3DjXWDMqFf06XtbZ0RSOJ3PZdNTYu0nwVjaI4h3CJnMEN7Cb73QjUd1GYnLcdfgUW39z828dAXvsgVBT7OljUg
### PUT CHANGE INNER CATEGORY STATUS
PUT http://localhost:8081/innerCategory/changeStatus/13
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQxMzIyMzksInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQyMTg2MzksImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.3DjXWDMqFf06XtbZ0RSOJ3PZdNTYu0nwVjaI4h3CJnMEN7Cb73QjUd1GYnLcdfgUW39z828dAXvsgVBT7OljUg
### DELET INNER CATEGORY WITH ID
DELETE http://localhost:8081/innerCategory/delete/13
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQxMzIyMzksInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQyMTg2MzksImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.3DjXWDMqFf06XtbZ0RSOJ3PZdNTYu0nwVjaI4h3CJnMEN7Cb73QjUd1GYnLcdfgUW39z828dAXvsgVBT7OljUg
### GET FOR UPDATE FROM ADMIN
GET http://localhost:8081/innerCategory/getByIdForUpdate/15
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQ1NTg4MzIsInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQ2NDUyMzIsImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.SDMl1q1BiHZslLLF2o0jiGtg3W2kEgXVfBp6MuUdcmpvXiSPF78-52hkEhLC35A5rSB7BRIT7J3_Uesfh3Bl1g
### GET CATEGORY FOR UPDATE FROM ADMIN WITH PAGINATION
GET http://localhost:8081/innerCategory/getListAll/1?page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQ1NTg4MzIsInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQ2NDUyMzIsImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.SDMl1q1BiHZslLLF2o0jiGtg3W2kEgXVfBp6MuUdcmpvXiSPF78-52hkEhLC35A5rSB7BRIT7J3_Uesfh3Bl1g