### CREATE INNER CATEGORY
POST http://localhost:8081/innerCategory/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzQxMzIyMzksInVzZXJuYW1lIjoiYWJkdWhha2ltXzEyMzQ1Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzQyMTg2MzksImlzcyI6IllvdVR1YmUgYnkgVGVhbVNlY3JldCJ9.3DjXWDMqFf06XtbZ0RSOJ3PZdNTYu0nwVjaI4h3CJnMEN7Cb73QjUd1GYnLcdfgUW39z828dAXvsgVBT7OljUg

{
  "photo": 2,
  "category": 1,
  "nameUz": "bigman",
  "nameRu": "Сладости111111",
  "descriptionUz": "Medovik tortlar",
  "descriptionRu": "Торты Медовик"

}

### UPDATE INNER CATEGORY
PUT http://localhost:8081/innerCategory/update/1
Content-Type: application/json
Authorization: Bearer

{
  "photo": 2,
  "category": 1,
  "nameUz": "Shirinliklar Update",
  "nameRu": "Сладости Update",
  "descriptionUz": "Medovik tortlar Update",
  "descriptionRu": "Торты Медовик Update"
}

### GET INNER CATEGORY WITH PAGENATION
GET http://localhost:8081/innerCategory/public/getList/UZ?page=0&size=5
### DELET INNER CATEGORY WITH ID
DELETE http://localhost:8081/innerCategory/delete/1

